mirrors/Makefile.am
mirrors/china/mirror.nyist.edu.cn
mirrors/china/mirrors.njupt.edu.cn
mirrors/china/mirrors.sau.edu.cn
mirrors/china/mirrors.scau.edu.cn
mirrors/china/mirrors.sdu.edu.cn
mirrors/china/mirrors.sustech.edu.cn
mirrors/europe/mirrors.sahilister.in
mirrors/europe/termux.astra.in.ua
mirrors/europe/termux.sahilister.in

https://github.com/termux/termux-packages/wiki/Mirrors

mirrors: Add missing mirrors

---

scripts/termux-change-repo.in

termux-change-repo.in: fixing a bug while working with pkg

---

mirrors/Makefile.am
mirrors/asia/linux.domainesia.com
mirrors/asia/mirror.nevacloud.com

https://github.com/termux/termux-packages/issues/11763

mirrors: add DomaiNesia and Nevacloud mirror

---

mirrors/Makefile.am
mirrors/europe/mirror.accum.se

In Umeå, Sweden. Updated every 4 hours.

mirrors: add mirror.accum.se

---

termux.properties

This one's similar to what I use on my device. Does properly showcase how to use the extra keys configuration and take it to the next level depending on how the workflow is of the user. Won't merge without feedback of others

chore: add new example key configuration

---

scripts/pkg.in

pkg: Restore `pkg up`

---

mirrors/Makefile.am
mirrors/asia/mirror.textcord.xyz

https://github.com/termux/termux-packages/issues/14326

mirrors: add mirror.textcord.xyz

---

scripts/pkg.in

Adding information about the `update` command and now the package format will change depending on the default package manager.

scripts/pkg.in: improved help message

---

scripts/termux-info.in

I think we'll need it at some point.

add(termux-info): Output of variable `LD_LIBRARY_PATH` and `LD_PRELOAD`

---

mirrors/Makefile.am
mirrors/oceania/mirrors.wale.id.au
scripts/pkg.in
scripts/termux-change-repo.in

First mirror (that we know of) added in https://github.com/termux/termux-packages/issues/15052

Add mirror group for Oceania

---

mirrors/Makefile.am
mirrors/europe/md.mirrors.hacktegic.com

https://github.com/termux/termux-packages/issues/15168

mirrors: add md.mirrors.hacktegic.com

---

mirrors/Makefile.am
mirrors/europe/ftp.fau.de

https://github.com/termux/termux-packages/issues/15873

mirrors: add ftp.fau.de

---

configure.ac
mirrors/Makefile.am
mirrors/north_america/mirror.quantum5.ca

mirrors: add mirror.quantum5.ca

---

mirrors/Makefile.am
mirrors/europe/is.mirror.flokinet.net
mirrors/europe/ro.mirror.flokinet.net

mirrors: add {ro,is}.mirror.flokinet.net

---

configure.ac
mirrors/Makefile.am
mirrors/europe/mirrors.medzik.dev

mirrors: add mirrors.medzik.dev

---

configure.ac
mirrors/Makefile.am
mirrors/europe/mirror.sunred.org

https://github.com/termux/termux-packages/issues/18398

mirrors: add mirror.sunred.org

---

configure.ac
mirrors/Makefile.am
mirrors/china/mirrors.qvq.net.cn

mirrors: add mirrors.qvq.net.cn

---

mirrors/Makefile.am
mirrors/europe/mirror.autkin.net

Hi, please kindly consider my mirror.

mirrors: add mirror.autkin.net

---

configure.ac
mirrors/Makefile.am
mirrors/europe/mirror.bouwhuis.network

mirrors: mirror.bouwhuis.network

---

configure.ac
mirrors/Makefile.am
mirrors/china/mirrors.aliyun.com
mirrors/china/mirrors.cqupt.edu.cn
mirrors/china/mirrors.dgut.edu.cn
mirrors/china/mirrors.hit.edu.cn
mirrors/china/mirrors.njupt.edu.cn
mirrors/china/mirrors.scau.edu.cn
mirrors/china/mirrors.ustc.edu.cn
mirrors/europe/mirror.leitecastro.com

mirrors: add mirror.leitecastro.com, mirrors: update chinese mainland mirrors 

---

configure.ac
mirrors/Makefile.am
mirrors/asia/mirror.freedif.org

mirrors: add mirror.freedif.org

---

mirrors/Makefile.am
mirrors/north_america/termux.danyael.xyz

https://github.com/termux/termux-tools/issues/90

mirrors: add termux.danyael.xyz

---

mirrors/Makefile.am
mirrors/asia/mirrors.in.sahilister.net
mirrors/europe/mirrors.de.sahilister.net
mirrors/europe/mirrors.sahilister.in

Closes https://github.com/termux/termux-tools/issues/97.

Add IN mirror; Change DE mirror URL

---

mirrors/Makefile.am
mirrors/asia/mirrors.saswata.xyz

Adding mirrors.saswata.xyz

---

configure.ac
mirrors/Makefile.am
mirrors/north_america/gnlug.org

mirrors: add gnlug.org

---

mirrors/Makefile.am
mirrors/oceania/mirror.endianness.com
mirrors/oceania/mirrors.middlendian.com

I received an email about the change, but lost track of it during vacation.

mirrors: oceania: fix url of DiffieHellman's mirror

---

scripts/termux-open.in
scripts/termux-reload-settings.in
scripts/termux-reset.in
scripts/termux-setup-storage.in
scripts/termux-wake-lock.in
scripts/termux-wake-unlock.in

I believe that this variable isn't used consistently across scripts/.
"Draft" because I'd like to test it more thoroughly.

scripts: replace com.termux with @TERMUX_APP_PACKAGE@

---

Makefile.am
configure.ac
scripts/Makefile.am
src/Makefile.am
src/cmd.c

scripts/cmd: Replace shell script with implementation in c

---

mirrors/Makefile.am
mirrors/asia/mirrors.omsinchan.ac.th

mirrors: add mirrors.omsinchan.ac.th

---

mirrors/Makefile.am
mirrors/south_america/mirrors.rda.run
scripts/pkg.in
scripts/termux-change-repo.in

mirrors: remove mirrors.rda.run

---

mirrors/Makefile.am
mirrors/asia/termux.niranjan.co

mirrors: add termux.niranjan.co

---

mirrors/Makefile.am
mirrors/asia/mirrors.saswata.cc
mirrors/asia/mirrors.saswata.xyz

Just changing the domain, Everything else is the same.
Regards

Modify domain to saswata.cc from saswata.xyz

---

mirrors/Makefile.am
mirrors/asia/mirror.jeonnam.school

mirrors: add mirror.jeonnam.school

---

mirrors/Makefile.am
mirrors/asia/mirror.rinarin.dev

mirrors: add mirror.rinarin.dev

---

mirrors/Makefile.am
mirrors/asia/mirrors.krnk.org

mirrors: add mirrors.krnk.org

---

mirrors/Makefile.am
mirrors/chinese_mainland/mirrors.cernet.edu.cn

https://mirrors.cernet.edu.cn/about

mirrors: add mirrors.cernet.edu.cn

---

configure.ac
mirrors/Makefile.am
mirrors/asia/mirror.meowsmp.net

mirrors: add mirror.meowsmp.net

---

scripts/chsh.in
scripts/login.in

Also: fix(scripts/chsh.in): allow passing absolute path to shell
Closes #140

fix(scripts/login.in): don't canonicalize symlink value

---

mirrors/Makefile.am
mirrors/europe/mirror.cutie.dating

mirrors: add mirror.cutie.dating
